### ISSUE TITLE
Default leapseconds file to /usr/share/zoneinfo/leap-seconds.list on Debian platforms

### ISSUE THREAD

**Issue by hrak** [sous-chefs/ntp#217]
## :ghost: Brief Description

This cookbook currently supplies its own (constantly expired) leapseconds file without a way of overriding the cookbook file in a wrapper cookbook. Debian based distro's already have an up-to-date file in `/usr/share/zoneinfo/leap-seconds.list` supplied and automatically updated by the tzdata package.

Please default to that for Debian based platforms, and maybe provide a way for wrapper cookbooks to easily supply their own. It saves you from having to maintain the leapseconds file in this cookbook.

I am aware that you can use a leapseconds mirror, but currently this cookbook defaults to an expired leapseconds file.

## :pancakes: Cookbook version

3.12.4

## :woman_cook:  Chef-Infra Version

17.10.3

## :tophat: Platform details

Operating system distribution and release version. Cloud provider if running in the cloud.

Ubunu 22.04

**Comment by hrak** [comment]
Apparently Redhat based platforms have their leapseconds file at `/usr/share/zoneinfo/leapseconds`, so this could apply to those as well.

**Comment by bugoff** [comment]
@hrak do you know if this also matches fedora and amazon? There is already a case for this, so i could add it to this

when 'rhel', 'fedora', 'amazon'
  default['ntp']['packages'] = %w(ntp ntpdate) if node['platform_version'].to_i >= 7
  default['ntp']['driftfile'] = "#{node['ntp']['varlibdir']}/drift"

**Comment by damacus** [comment]
Closed via https://github.com/sous-chefs/ntp/pull/242
